config/routes.rb
MyRailsBlog::Application.routes.draw do
  resources :companies

  resources :projects

  resources :addresses

  resources :skills

  resources :languages

  resources :educational_qualifications

  resources :experiences

  resources :resumes

  devise_for :users
  resources :users

  root "welcome#index"

  

end

app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :user
end

app/models/company.rb
class Company < ActiveRecord::Base
	belongs_to :user
	has_many :projects
	belongs_to :experience
end

app/models/educational_qualification.rb
class EducationalQualification < ActiveRecord::Base
	belongs_to :user
end

app/models/experience.rb
class Experience < ActiveRecord::Base
	belongs_to :user
	has_many :companies
end

app/models/language.rb
class Language < ActiveRecord::Base
	belongs_to :user
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :imageable, :polymorphic => true
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/	
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user
	belongs_to :company

end

app/models/resume.rb
class Resume < ActiveRecord::Base
	belongs_to :user
	has_many :pictures, :as => :imageable
end

app/models/skill.rb
class Skill < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pictures, :as => :imageable
  has_many :resumes
  has_many :skills
  has_many :addresses
  has_many :languages
  has_many :educational_qualifications
  has_many :experiences
  has_many :projects
  has_many :companies
end

app/controllers/educational_qualifications_controller.rb
class EducationalQualificationsController < ApplicationController
  before_action :set_educational_qualification, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  respond_to :html

  def index
    @educational_qualifications = EducationalQualification.all
    respond_with(@educational_qualifications)
  end

  def show
    respond_with(@educational_qualification)
  end

  def new
    @educational_qualification = current_user.educational_qualifications.build
    respond_with(@educational_qualification)
  end

  def edit
  end

  def create
    @educational_qualification = current_user.educational_qualifications.build(educational_qualification_params)
    @educational_qualification.save
    respond_with(@educational_qualification)
  end

  def update
    @educational_qualification.update(educational_qualification_params)
    respond_with(@educational_qualification)
  end

  def destroy
    @educational_qualification.destroy
    respond_with(@educational_qualification)
  end

  private
    def set_educational_qualification
      @educational_qualification = EducationalQualification.find(params[:id])
    end

    def educational_qualification_params
      params.require(:educational_qualification).permit(:college, :course, :subject, :start_date, :end_date, :percentage, :user_id, :resume_id, :city, :state, :country, :rollnumber)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    binding.pry
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :user_name, :admin, :role, :email1, :email2, :phone, :present_job, :present_city)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
	def exp
		Hash[Experience.all.pluck(:id, :company)]
	end		
end

app/helpers/educational_qualifications_helper.rb
module EducationalQualificationsHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
	def companies
		Hash[Company.all.pluck(:id, :name)]
	end
end

app/helpers/resumes_helper.rb
module ResumesHelper
	def exper
		a = "Expertise in Ruby on Rails Framework.
Expertise in MVC web application development.
Expertise in JavaScript, angular js.
Good experience in handling project individually.
Good experience in object oriented approach.
Good experience in git.
Good experience in mongodb.
Experience in redis."		
	end

	def objective
		a = "A self-motivated IT professional with huge knowledge and proficiency in ​ Ruby, Rails, Html,
CSS, JavaScript and Angularjs​ , as well as strong skills and ability in writing clean and efficient
code, seeks the position of Software Engineer."
	end

	def objective_1
		a = "Talented individual with strong communication skills, team spirit, and Masters in Computer Science desires the position of Software Developer at Pronto Networks (Stanford Wireless Private Limited). Bringing expertise in writing full-stack code to support multiple platforms and object- oriented designs."
	end

	def objective_2
		a = " Experienced tech professional vast in Ruby, RAILS, CSS, HTML, JavaScript. Looking to obtain the role of Software Developer at  Pronto Networks (Stanford Wireless Private Limited). to utilize 3.7 years of experience in handling popular web languages and Java script in developing and implementing applications based on clients’ need."
	end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/educational_qualifications/_form.html.erb
<%= form_for(@educational_qualification) do |f| %>
  <% if @educational_qualification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@educational_qualification.errors.count, "error") %> prohibited this educational_qualification from being saved:</h2>

      <ul>
      <% @educational_qualification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :college %><br>
    <%= f.text_field :college %>
  </div>
  <div class="field">
    <%= f.label :course %><br>
    <%= f.text_field :course %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date, { :include_blank => true, :start_year => 2000 } %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date, { :include_blank => true, :start_year => 2000 } %>
  </div>
  <div class="field">
    <%= f.label :percentage %><br>
    <%= f.text_field :percentage %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :resume_id %><br>
    <%= f.number_field :resume_id %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :rollnumber %><br>
    <%= f.text_field :rollnumber %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/educational_qualifications/edit.html.erb
<h1>Editing educational_qualification</h1>

<%= render 'form' %>

<%= link_to 'Show', @educational_qualification %> |
<%= link_to 'Back', educational_qualifications_path %>

app/views/educational_qualifications/index.html.erb
<h1>Listing educational_qualifications</h1>

<table>
  <thead>
    <tr>
      <th>College</th>
      <th>Course</th>
      <th>Subject</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Percentage</th>
      <th>User</th>
      <th>Resume</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th>Rollnumber</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @educational_qualifications.each do |educational_qualification| %>
      <tr>
        <td><%= educational_qualification.college %></td>
        <td><%= educational_qualification.course %></td>
        <td><%= educational_qualification.subject %></td>
        <td><%= educational_qualification.start_date %></td>
        <td><%= educational_qualification.end_date %></td>
        <td><%= educational_qualification.percentage %></td>
        <td><%= educational_qualification.user_id %></td>
        <td><%= educational_qualification.resume_id %></td>
        <td><%= educational_qualification.city %></td>
        <td><%= educational_qualification.state %></td>
        <td><%= educational_qualification.country %></td>
        <td><%= educational_qualification.rollnumber %></td>
        <td><%= link_to 'Show', educational_qualification %></td>
        <td><%= link_to 'Edit', edit_educational_qualification_path(educational_qualification) %></td>
        <td><%= link_to 'Destroy', educational_qualification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Educational qualification', new_educational_qualification_path %>

app/views/educational_qualifications/new.html.erb
<h1>New educational_qualification</h1>

<%= render 'form' %>

<%= link_to 'Back', educational_qualifications_path %>

app/views/educational_qualifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>College:</strong>
  <%= @educational_qualification.college %>
</p>

<p>
  <strong>Course:</strong>
  <%= @educational_qualification.course %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @educational_qualification.subject %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @educational_qualification.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @educational_qualification.end_date %>
</p>

<p>
  <strong>Percentage:</strong>
  <%= @educational_qualification.percentage %>
</p>

<p>
  <strong>User:</strong>
  <%= @educational_qualification.user_id %>
</p>

<p>
  <strong>Resume:</strong>
  <%= @educational_qualification.resume_id %>
</p>

<p>
  <strong>City:</strong>
  <%= @educational_qualification.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @educational_qualification.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @educational_qualification.country %>
</p>

<p>
  <strong>Rollnumber:</strong>
  <%= @educational_qualification.rollnumber %>
</p>

<%= link_to 'Edit', edit_educational_qualification_path(@educational_qualification) %> |
<%= link_to 'Back', educational_qualifications_path %>