config/routes.rb
MyRailsBlog::Application.routes.draw do
  resources :companies

  resources :projects

  resources :addresses

  resources :skills

  resources :languages

  resources :educational_qualifications

  resources :experiences

  resources :resumes

  devise_for :users
  resources :users

  root "welcome#index"

  

end

app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :user
end

app/models/company.rb
class Company < ActiveRecord::Base
	belongs_to :user
	has_many :projects
	belongs_to :experience
end

app/models/experience.rb
class Experience < ActiveRecord::Base
	belongs_to :user
	has_many :companies
end

app/models/language.rb
class Language < ActiveRecord::Base
	belongs_to :user
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :imageable, :polymorphic => true
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/	
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user
	belongs_to :company

end

app/models/resume.rb
class Resume < ActiveRecord::Base
	belongs_to :user
	has_many :pictures, :as => :imageable
end

app/models/skill.rb
class Skill < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pictures, :as => :imageable
  has_many :resumes
  has_many :skills
  has_many :addresses
  has_many :languages
  has_many :educational_qualifications
  has_many :experiences
  has_many :projects
  has_many :companies
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :set_resume, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]
  respond_to :html

  def index
    @resumes = Resume.all
    respond_with(@resumes)
  end

  def show
    respond_with(@resume)
  end

  def new
    @resume = current_user.resumes.build
    respond_with(@resume)
  end

  def edit
  end

  def create
    @resume = current_user.resumes.build(resume_params)
    @resume.save
    if @resume.present? && params["resume"]["image"].present?
      @resume.pictures.present? ? @resume.pictures.delete_all : []
      @resume.pictures.create(:image => params["resume"]["image"], :image_value => "1")
    end  
    respond_with(@resume)
  end

  def update
    @resume.update(resume_params)
    if @resume.present? && params["resume"]["image"].present?
      if @resume.pictures.where(:image_value => "1").present? 
        
        @resume.pictures.where(:image_value => "1").present? ? @resume.pictures.where(:image_value => "1").delete_all : []
        @resume.pictures.create(:image => params["resume"]["image"])
      else
        @resume.pictures.create(:image => params["resume"]["image"], :image_value => "1")
      end
    end 
    respond_with(@resume)
  end

  def destroy
    @resume.destroy
    respond_with(@resume)
  end

  private
    def set_resume
      @resume = Resume.find(params[:id])
    end

    def resume_params
      params.require(:resume).permit(:name, :description)
    end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  respond_to :html

  def index
    @skills = Skill.all
    respond_with(@skills)
  end

  def show
    respond_with(@skill)
  end

  def new
    @skill = current_user.skills.build
    respond_with(@skill)
  end

  def edit
  end

  def create
    @skill = current_user.skills.build(skill_params)
    @skill.save
    respond_with(@skill)
  end

  def update
    @skill.update(skill_params)
    respond_with(@skill)
  end

  def destroy
    @skill.destroy
    respond_with(@skill)
  end

  private
    def set_skill
      @skill = Skill.find(params[:id])
    end

    def skill_params
      params.require(:skill).permit(:name, :version, :last_used, :project, :percentage, :expert_level, :user_id, :resume_id, :company_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    binding.pry
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :user_name, :admin, :role, :email1, :email2, :phone, :present_job, :present_city)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
	def exp
		Hash[Experience.all.pluck(:id, :company)]
	end		
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
	def companies
		Hash[Company.all.pluck(:id, :name)]
	end
end

app/helpers/resumes_helper.rb
module ResumesHelper
	def exper
		a = "Expertise in Ruby on Rails Framework.
Expertise in MVC web application development.
Expertise in JavaScript, angular js.
Good experience in handling project individually.
Good experience in object oriented approach.
Good experience in git.
Good experience in mongodb.
Experience in redis."		
	end

	def objective
		a = "A self-motivated IT professional with huge knowledge and proficiency in ​ Ruby, Rails, Html,
CSS, JavaScript and Angularjs​ , as well as strong skills and ability in writing clean and efficient
code, seeks the position of Software Engineer."
	end

	def objective_1
		a = "Talented individual with strong communication skills, team spirit, and Masters in Computer Science desires the position of Software Developer at Pronto Networks (Stanford Wireless Private Limited). Bringing expertise in writing full-stack code to support multiple platforms and object- oriented designs."
	end

	def objective_2
		a = " Experienced tech professional vast in Ruby, RAILS, CSS, HTML, JavaScript. Looking to obtain the role of Software Developer at  Pronto Networks (Stanford Wireless Private Limited). to utilize 3.7 years of experience in handling popular web languages and Java script in developing and implementing applications based on clients’ need."
	end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/resumes/_form.html.erb
<%= form_for(@resume) do |f| %>
  <% if @resume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resume.errors.count, "error") %> prohibited this resume from being saved:</h2>

      <ul>
      <% @resume.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description%>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>  
  <%= f.hidden_field :form_type, :value => "1" %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resumes/edit.html.erb
<h1>Editing resume</h1>

<%= render 'form' %>

<%= link_to 'Show', @resume %> |
<%= link_to 'Back', resumes_path %>

app/views/resumes/index.html.erb
  <div class="w3-container">
  <%= link_to 'New Resume',new_resume_path ,  :class => 'w3-button w3-red w3-card-4'%>
  <div class="w3-panel w3-card">
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @resumes.each do |resume| %>
            <tr>
              <td><%= resume.name %></td>
              <td><%= link_to 'Show', resume %></td>
              <td><%= link_to 'Edit', edit_resume_path(resume) %></td>
              <td><%= link_to 'Destroy', resume, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>    
  </div>

      

   

    <button onclick="myFunction('Demo1')" class="w3-button w3-block w3-teal w3-left-align">Skills</button>
    <div id="Demo1" class="w3-hide w3-container">
        <table class="w3-table w3-striped w3-bordered w3-border w3-hoverable w3-white">
          <%Skill.all.each do |sk|%>
          <tr>
            <td><%= sk.name %></td>
    <!--          <td><button type="button" class="w3-button w3-theme"><i class="fa fa-pencil"></i></button> </td> -->
             <td><%= link_to 'Edit', edit_skill_path(sk) %></td>
          </tr>
          <%end%>
        </table><br>
    </div>
    <button onclick="myFunction('Demo2')" class="w3-button w3-block w3-teal w3-left-align">Projects</button>
    <div id="Demo2" class="w3-hide w3-container">
        <table class="w3-table w3-striped w3-bordered w3-border w3-hoverable w3-white">
          <%Project.all.each do |pro|%>
          <tr>
            <td><%= pro.name %></td>
             <td><%= link_to 'Edit', edit_project_path(pro) %></td>
          </tr>
          <%end%>
        </table><br>
    </div>    
    <button onclick="myFunction('Demo3')" class="w3-button w3-block w3-teal w3-left-align">Companies</button>
    <div id="Demo3" class="w3-hide w3-container">
        <table class="w3-table w3-striped w3-bordered w3-border w3-hoverable w3-white">
          <%Company.all.each do |pro|%>
          <tr>
            <td><%= pro.name %></td>
             <td><%= link_to 'Edit', edit_company_path(pro) %></td>
          </tr>
          <%end%>
        </table><br>
    </div>    
    <button onclick="myFunction('Demo4')"class="w3-button w3-block w3-teal w3-left-align">Qualification</button>
    <div id="Demo4" class="w3-hide w3-container">
        <table class="w3-table w3-striped w3-bordered w3-border w3-hoverable w3-white">
          <%EducationalQualification.all.each do |pro|%>
          <tr>
            <td><%= pro.course %></td>
             <td><%= link_to 'Edit', edit_educational_qualification_path(pro) %></td>
          </tr>
          <%end%>
        </table><br>
    </div>   
    <button onclick="myFunction('Demo5')"class="w3-button w3-block w3-teal w3-left-align">Address</button>
    <div id="Demo5" class="w3-hide w3-container">
        <table class="w3-table w3-striped w3-bordered w3-border w3-hoverable w3-white">
          <%Address.all.each do |pro|%>
          <tr>
            <td><%= pro.city %></td>
             <td><%= link_to 'Edit', edit_address_path(pro) %></td>
          </tr>
          <%end%>
        </table><br>
    </div>  
    <button onclick="myFunction('Demo6')"class="w3-button w3-block w3-teal w3-left-align">Language</button>
    <div id="Demo6" class="w3-hide w3-container">
        <table class="w3-table w3-striped w3-bordered w3-border w3-hoverable w3-white">
          <%Language.all.each do |pro|%>
          <tr>
            <td><%= pro.name %></td>
             <td><%= link_to 'Edit', edit_language_path(pro) %></td>
          </tr>
          <%end%>
        </table><br>
    </div>               
  </div>

<script>
// Get the Sidebar
var mySidebar = document.getElementById("mySidebar");

// Get the DIV with overlay effect
var overlayBg = document.getElementById("myOverlay");

// Toggle between showing and hiding the sidebar, and add overlay effect
function w3_open() {
  if (mySidebar.style.display === 'block') {
    mySidebar.style.display = 'none';
    overlayBg.style.display = "none";
  } else {
    mySidebar.style.display = 'block';
    overlayBg.style.display = "block";
  }
}

// Close the sidebar with the close button
function w3_close() {
  mySidebar.style.display = "none";
  overlayBg.style.display = "none";
}

function myFunction(id) {
  var x = document.getElementById(id);
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
    x.previousElementSibling.className = 
    x.previousElementSibling.className.replace("w3-black", "w3-red");
  } else { 
    x.className = x.className.replace(" w3-show", "");
    x.previousElementSibling.className = 
    x.previousElementSibling.className.replace("w3-red", "w3-black");
  }
}
</script>
</body>

app/views/resumes/new.html.erb
<h1>New resume</h1>

<%= render 'form' %>

<%= link_to 'Back', resumes_path %>

app/views/resumes/show.html.erb
<script>
function myFunction(id) {
  var x = document.getElementById(id);
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else { 
    x.className = x.className.replace(" w3-show", "");
  }
}
</script>
<body class="w3-light-grey">

<!-- Page Container -->
<div class="w3-content w3-margin-top" style="max-width:1400px;">

  <!-- The Grid -->
  <div class="w3-row-padding">
  
    <!-- Left Column -->
    <div class="w3-third">
    
      <div class="w3-white w3-text-grey w3-card-4">
        <div class="w3-display-container">
          <%= image_tag "me.jpg", :class => "style_image" %>
          <div class="w3-display-bottomleft w3-container w3-text-black">
            <h2><%= @resume.user.name %></h2>
          </div>
        </div>
        <div class="w3-container">
          <p><i class="fa fa-briefcase fa-fw w3-margin-right w3-large w3-text-teal"></i><%= @resume.user.present_job %></p>
          <p><i class="fa fa-home fa-fw w3-margin-right w3-large w3-text-teal"></i><%= @resume.user.present_city %></p>
          <p><i class="fa fa-envelope fa-fw w3-margin-right w3-large w3-text-teal"></i><%= @resume.user.email1 %></p>
          <p><i class="fa fa-phone fa-fw w3-margin-right w3-large w3-text-teal"></i><%= @resume.user.phone %></p>
          <hr>

          <p class="w3-large"><b><i class="fa fa-asterisk fa-fw w3-margin-right w3-text-teal"></i>Skills</b></p>
          
		      <% @resume.user.skills.each do |sk|%>
          <span class="w3-tag w3-small w3-teal"><%= sk.name %></span>
		      <% end %>     

          <br>
          <hr>
          <p class="w3-large w3-text-theme"><b><i class="fa fa-globe fa-fw w3-margin-right w3-text-teal"></i>Languages</b></p>
          <% @resume.user.languages.each do |la| %>
          <span class="w3-tag w3-small w3-teal"><%= la.name %></span>
          <% end %>
          <br><hr>
          <p class="w3-large"><b><i class="fa fa-asterisk fa-fw w3-margin-right w3-text-teal"></i>Objective:</b></p>
          <div class="w3-panel w3-card w3-teal"><h6><%= objective%></h6></div>
          <br>
          <hr>
          <p class="w3-large"><b><i class="fa fa-asterisk fa-fw w3-margin-right w3-text-teal"></i>Expertize:</b></p>
          <% exper.split('.').each do |sk|%>
          <h6><%= sk.strip %></h6>
          <% end %>           
        </div>
      </div><br>

    <!-- End Left Column -->
    </div>

    <!-- Right Column -->
    <div class="w3-twothird">
    
      <div class="w3-container w3-card w3-white w3-margin-bottom">
        <h2 class="w3-text-grey w3-padding-16"><i class="fa fa-suitcase fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i>Work Experience</h2>

      		<% @resume.user.experiences.each do |exp|%>
      		<% val = (exp.present == true) ? ("w3-tag w3-teal w3-round") : "" %>
      		<% vall = (exp.present == true) ? "current" : exp.end_date.strftime("%B %Y") %>
      	        <div class="w3-container">
      	          <h5 class="w3-opacity"><b><%= exp.role %> / <%= exp.company %></b></h5>
      	          <h6 class="w3-text-teal"><i class="fa fa-calendar fa-fw w3-margin-right"></i><%= exp.start_date.strftime("%B %Y") %> - 
      	           <%= tag :span, :class => "#{val}" %> <%= vall %></h6>
                   <% exp.companies.map {|i| i.projects}.flatten.each do |pro| %>
                    <div class="w3-card-4" style="width:100%;">
                      <header class="w3-container w3-teal">
                        <h5><%= pro.name %></h5>
                      </header>
                      <div class="w3-container">
                        <p><%= pro.description%></p>
                        <div class="w3-card-4" style="width:100%;">
                          <h5 class="w3-container w3-teal">
                            <h4 class="w3-container w3-medium ">Responsibility </h4>
                          </h5>                            
                            <% if pro.achievements.present? %>
                            <div class = "w3-pale-red">
                            <ul>
                             <% pro.achievements.split('.').each do |ach| %>
                             <li><p><%= ach.strip %></p></li>
                             <% end %>                    
                            <% end %>  
                            </ul>
                          </div>

                        </div>                        
                      </div>
                    </div><br>
                  <% end %> 
      	          <hr>
      	        </div>
      		<% end %>
	     </div>

      <div class="w3-container w3-card w3-white">
        <h2 class="w3-text-grey w3-padding-16"><i class="fa fa-certificate fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i>Education</h2>
   		<%@resume.user.educational_qualifications.each do |ed|%>
        <table class="w3-table w3-striped w3-bordered w3-border">
        <thead class="w3-teal"><th style="width:30%">Institute</th><th style="width:20%">Course</th><th style="width:20%">Subject</th><th  style="width:30%">Percentage</th><th style="width:20%">Year</th></thead>
        <tr><td><%= ed.college%></td><td><%=ed.course %></td><td><%= ed.subject %></td><td><%=ed.percentage%></td><td><%= ed.end_date.strftime("%B %Y") %></td></tr>
        </table>
    	<% end %>
    <!-- End Right Column -->
    </div>
    
  <!-- End Grid -->
  </div>
  
  <!-- End Page Container -->
</div>



</body>

app/views/skills/_form.html.erb
<%= form_for(@skill) do |f| %>
  <% if @skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@skill.errors.count, "error") %> prohibited this skill from being saved:</h2>

      <ul>
      <% @skill.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :version %><br>
    <%= f.text_field :version %>
  </div>
  <div class="field">
    <%= f.label :last_used %><br>
    <%= f.date_select :last_used %>
  </div>
  <div class="field">
    <%= f.label :project %><br>
    <%= f.text_field :project %>
  </div>
  <div class="field">
    <%= f.label :percentage %><br>
    <%= f.number_field :percentage %>
  </div>
  <div class="field">
    <%= f.label :expert_level %><br>
    <%= f.text_field :expert_level %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :resume_id %><br>
    <%= f.number_field :resume_id %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br>
    <%= f.number_field :company_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/skills/edit.html.erb
<h1>Editing skill</h1>

<%= render 'form' %>

<%= link_to 'Show', @skill %> |
<%= link_to 'Back', skills_path %>

app/views/skills/index.html.erb
<h1>Listing skills</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Version</th>
      <th>Last used</th>
      <th>Project</th>
      <th>Percentage</th>
      <th>Expert level</th>
      <th>User</th>
      <th>Resume</th>
      <th>Company</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @skills.each do |skill| %>
      <tr>
        <td><%= skill.name %></td>
        <td><%= skill.version %></td>
        <td><%= skill.last_used %></td>
        <td><%= skill.project %></td>
        <td><%= skill.percentage %></td>
        <td><%= skill.expert_level %></td>
        <td><%= skill.user_id %></td>
        <td><%= skill.resume_id %></td>
        <td><%= skill.company_id %></td>
        <td><%= link_to 'Show', skill %></td>
        <td><%= link_to 'Edit', edit_skill_path(skill) %></td>
        <td><%= link_to 'Destroy', skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Skill', new_skill_path %>

app/views/skills/new.html.erb
<h1>New skill</h1>

<%= render 'form' %>

<%= link_to 'Back', skills_path %>

app/views/skills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @skill.name %>
</p>

<p>
  <strong>Version:</strong>
  <%= @skill.version %>
</p>

<p>
  <strong>Last used:</strong>
  <%= @skill.last_used %>
</p>

<p>
  <strong>Project:</strong>
  <%= @skill.project %>
</p>

<p>
  <strong>Percentage:</strong>
  <%= @skill.percentage %>
</p>

<p>
  <strong>Expert level:</strong>
  <%= @skill.expert_level %>
</p>

<p>
  <strong>User:</strong>
  <%= @skill.user_id %>
</p>

<p>
  <strong>Resume:</strong>
  <%= @skill.resume_id %>
</p>

<p>
  <strong>Company:</strong>
  <%= @skill.company_id %>
</p>

<%= link_to 'Edit', edit_skill_path(@skill) %> |
<%= link_to 'Back', skills_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :admin %><br>
    <%= f.check_box :admin %>
  </div>
  <div class="field">
    <%= f.label :role %><br>
    <%= f.text_field :role %>
  </div>
  <div class="field">
    <%= f.label :email1 %><br>
    <%= f.text_field :email1 %>
  </div>
  <div class="field">
    <%= f.label :email2 %><br>
    <%= f.text_field :email2 %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :present_city %>
  </div>
  <div class="field">
    <%= f.label :job %><br>
    <%= f.text_field :present_job %>
  </div>  
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
    
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User name</th>
      <th>Admin</th>
      <th>Role</th>
      <th>Email1</th>
      <th>Email2</th>
      <th>Phone</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.user_name %></td>
        <td><%= user.admin %></td>
        <td><%= user.role %></td>
        <td><%= user.email1 %></td>
        <td><%= user.email2 %></td>
        <td><%= user.phone %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>User name:</strong>
  <%= @user.user_name %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @user.admin %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<p>
  <strong>Email1:</strong>
  <%= @user.email1 %>
</p>

<p>
  <strong>Email2:</strong>
  <%= @user.email2 %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>